name: Release CI
on: workflow_dispatch
jobs:

  x64_build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Run msbuild
      run: |
        $env:_CL_=" /GA /GF /Gw /Gy /GL /Ox /Ob3 /Oi /Ot /Oy /Z7 /fp:fast /fpcvt:IA /jumptablerdata /guard:cf /arch:AVX512 /vlen=256 /w"
        $env:_LINK_=" /LTCG:INCREMENTAL /guard:longjmp /cetcompat /opt:ref,icf /filealign:4096 /release /subsystem:windows,10.0 /osversion:10.0"
        msbuild -p:configuration="Release (lite)" -p:platform=x64 -p:platformToolset=v145 -p:DebugSymbols=false -p:DebugType=None -p:DebugInformationFormat=0 -p:Optimization=Full -p:OmitFramePointers=true -p:FloatingPointModel=Fast -p:EnableEnhancedInstructionSet=AdvancedVectorExtensions512
      
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+08:00"
      
    - name : Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/x64/*/*.exe
